### ISSUE TITLE
Question : is the helm chart available on an helm repository ?

### ISSUE THREAD

**Issue by eddycharly** [hjacobs/kube-resource-report#115]
Is the helm chart distributed on a helm repository somewhere ?
Or do we have to clone this repository to install it ?

Thanks

**Comment by chetankapoor** [comment]
I installed it by cloning the repo. It's not available on helm repository.

**Comment by eddycharly** [comment]
@chetankapoor thanks, i did the same. just asked if @hjacobs hosted it somewhere on his own repo.

**Comment by hjacobs** [comment]
No, I'm not using Helm myself, so my support for Helm Charts is pretty basic.

**Comment by andrea-maruccia-leaseplan** [comment]
@hjacobs would it be possible to implement an helm index in this repo? Just like kube-janitor does here -> https://github.com/hjacobs/kube-janitor/blob/master/unsupported/helm/index.yaml
I could try to fork it and give a try if that's ok with you

**Comment by eddycharly** [comment]
FWIW setting up a helm repo with github actions is free and pretty easy.

**Comment by andrea-maruccia-leaseplan** [comment]
@eddycharly do you have an example somewhere?

**Comment by eddycharly** [comment]
you can look here https://github.com/eddycharly/tekton-helm
it uses github pages to host the index.yaml file and github releases to host packaged charts

**Comment by andrea-maruccia-leaseplan** [comment]
@eddycharly i found an easier way to deal with this:
- I installed this: https://github.com/aslafy-z/helm-git with `helm plugin install https://github.com/aslafy-z/helm-git`
- then in the helmfile (or helm) i just use this repo: 
`git+https://github.com/hjacobs/kube-resource-report@unsupported/chart/kube-resource-report` with chart 
`hjacobs-kube-resource-report/kube-resource-report`
Works like a charm. I guess versioning is also supported because you could reference a tag or branch but i've not tried that yet.

Here is my helmfile for reference:

```yaml
repositories:
- name: hjacobs-kube-resource-report
  url: git+https://github.com/hjacobs/kube-resource-report@unsupported/chart/kube-resource-report

releases:
  - name: kube-resource-report
    chart: hjacobs-kube-resource-report/kube-resource-report
    namespace: kube-system
    values:
    <snip>
```
